### ISSUE TITLE
Please update the particle library structure

### ISSUE THREAD

**Issue by wvdv2002** [jychuah/ParticleFtpClient#2]
Could you please update the particle library structure to the new one documented [here](https://docs.particle.io/guide/tools-and-features/libraries/). Please include my port select commit in that version of the library. This keeps me from uploading my [ftpfilesender](https://github.com/wvdv2002/Particle-FTPFileSender) library for now.
Thanks in advance.

**Comment by wvdv2002** [comment]
Hi Jychuah, 
Could you please take the time to update the version fo this library?
Thanks!

**Comment by jychuah** [comment]
Hi, wvdv2002. Sorry for the delay in response. Can you submit a pull request with your changes? Also, I updated the library structure but the CLI command particle library upload isn't working. I'm going to post to the community forums for help.

**Comment by wvdv2002** [comment]
Hi Jychuah,
No problem, it was just a reminder. There are no new changes to submit. The only problem is that the version 0.0.2 of your library did not yet incorporate the last commit I submitted where the TCP port can also be defined. I now see that you updated the version to 0.0.3, after you are able to publish it to the particle library system we should be in the clear.

**Comment by ScruffR** [comment]
@jychuah, I've now had the chance to talk to the master of libraries and CLI at Particle and he suggested to change the library name in the `library.properties` file to `ParticleFtpClient` as it was called in 0.0.2 but with 0.0.3 you named it `ParticleFTPClient` which causes the mismatch, but the error message you got when you tried didn't really help finding that issue ;-)

**Comment by jchuahtacc** [comment]
@ScruffR THANK YOU SO MUCH.

Updated the library and pushed it to Particle.io @wvdv2002 do you mind checking to see that you are able to import it?

**Comment by wvdv2002** [comment]
Sorry @jychuah, it does not work yet. Did you publish a new version using the particle library manager and did you make the new update public?

**Comment by wvdv2002** [comment]
You probably need to update to version 0.0.4 before you can upload it again, or did you never upload version 0.0.3 to the particle library manager?

**Comment by jchuahtacc** [comment]
@wvdv2002 I just didn't publish it. Try now.

**Comment by ScruffR** [comment]
I was able to import it in my project.

@wvdv2002, you may need to clear the Web IDE cache?
If you still get 0.0.2 you can also try to hit the (i) icon next to the github icon to select the version you actually want to use.
![image](https://user-images.githubusercontent.com/6604878/40433317-0a0340ae-5eac-11e8-85d8-40429e3286f0.png)

**Comment by wvdv2002** [comment]
Ok, I can now import it. One more bug to fix though, the files are now named ParticleFTPClient.* but the header file ParticleFtpClient.h is referenced in the cpp file haha. I would recommend renaming the files to ParticleFtpClient.*, as this is the name of the Github repo and the library.

**Comment by wvdv2002** [comment]
Almost there :persevere: :muscle:

**Comment by jchuahtacc** [comment]
Ok fixed it... and actually tested it this time lolol.

**Comment by wvdv2002** [comment]
Awesome, it works now. Thanks @jychuah  and @ScruffR.

**Comment by jchuahtacc** [comment]
Thanks to the both you, @wvdv2002 and @ScruffR
