### ISSUE TITLE
Example doesn't compile

### ISSUE THREAD

**Issue by nklugman** [jychuah/ParticleFtpClient#3]
I believe the example app needs to be updated with the new `ftp.open(hostname, timeout)` function signature.

**Comment by jchuahtacc** [comment]
The release on Particle.io is an older version. I'm having trouble getting the latest version of the library uploaded to Particle, where this is corrected. I'll leave this issue open until I can get the upload working.

**Comment by jchuahtacc** [comment]
Updated the library on Particle.io. The example compiles now.
